/**
 * SPEC-008 — POST /api/admin/spec-008/seed-fixture
 *
 * Used by the Playwright fixture in `tests/e2e/spec-008/governance-fixtures.ts`
 * to spin up a fresh per-test workspace + sample governance state.
 *
 * Body: `{ slug: string; flagOn: boolean }`
 * Returns: `{ workspaceId: number; agentIds: number[] }`
 *
 * Gated behind `MISSION_CONTROL_TEST_MODE=1` AND admin auth — see
 * `_shared/auth-gate.ts`.
 *
 * Tear-down lives at `seed-fixture/[id]/route.ts` (DELETE).
 */

import { NextResponse, type NextRequest } from 'next/server';
import { adminTestModeGate } from '../_shared/auth-gate';
import { seedSpec008Fixture } from '../_shared/fixture-seeder';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

interface SeedRequestBody {
  slug?: unknown;
  flagOn?: unknown;
  seedPolicies?: unknown;
}

function parseBody(raw: unknown): { slug: string; flagOn: boolean; seedPolicies?: boolean } | null {
  if (raw === null || typeof raw !== 'object') return null;
  const body = raw as SeedRequestBody;
  const slug =
    typeof body.slug === 'string' && body.slug.length > 0 && body.slug.length <= 64
      ? body.slug
      : null;
  if (slug === null) return null;
  if (!/^[a-z0-9][a-z0-9-]{0,63}$/.test(slug)) return null;
  const flagOn = body.flagOn === true;
  if (body.seedPolicies === false) return { slug, flagOn, seedPolicies: false };
  return { slug, flagOn };
}

export async function POST(request: NextRequest): Promise<NextResponse> {
  // Outer catch so any throw — including those from the gate or import-time
  // initialization — surfaces as a JSON 500 instead of an empty-body 500
  // generated by Next.js. This is essential for diagnosing failures during
  // SPEC-008 e2e bring-up; without it the response body is empty and tests
  // fail with no actionable signal.
  try {
    const gate = adminTestModeGate(request);
    if (!gate.ok) return gate.response;

    let bodyRaw: unknown;
    try {
      bodyRaw = await request.json();
    } catch {
      return NextResponse.json(
        { code: 'invalid_body', detail: 'POST body must be JSON' },
        { status: 400 },
      );
    }
    const parsed = parseBody(bodyRaw);
    if (parsed === null) {
      return NextResponse.json(
        { code: 'invalid_body', detail: 'expected { slug: string, flagOn: boolean }' },
        { status: 400 },
      );
    }
    const result = seedSpec008Fixture(parsed);
    return NextResponse.json(
      { workspaceId: result.workspaceId, agentIds: result.agentIds },
      { status: 201 },
    );
  } catch (err) {
    return NextResponse.json(
      {
        code: 'seed_failed',
        detail: err instanceof Error ? err.message : 'unknown',
        stack: err instanceof Error ? err.stack?.split('\n').slice(0, 6).join('\n') : undefined,
      },
      { status: 500 },
    );
  }
}
